# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './note.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 445)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TitleLine = QtWidgets.QLineEdit(self.centralwidget)
        self.TitleLine.setGeometry(QtCore.QRect(10, 30, 211, 32))
        self.TitleLine.setObjectName("TitleLine")
        self.AuthorLine = QtWidgets.QLineEdit(self.centralwidget)
        self.AuthorLine.setGeometry(QtCore.QRect(250, 30, 161, 32))
        self.AuthorLine.setObjectName("AuthorLine")
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(10, 10, 171, 18))
        self.TitleLabel.setObjectName("TitleLabel")
        self.TextLabel = QtWidgets.QLabel(self.centralwidget)
        self.TextLabel.setGeometry(QtCore.QRect(10, 70, 171, 18))
        self.TextLabel.setObjectName("TextLabel")
        self.AuthorLabel = QtWidgets.QLabel(self.centralwidget)
        self.AuthorLabel.setGeometry(QtCore.QRect(250, 10, 171, 18))
        self.AuthorLabel.setObjectName("AuthorLabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 330, 161, 34))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 90, 401, 231))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 425, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.save_note)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TitleLabel.setText(_translate("MainWindow", "Введите имя заметки:"))
        self.TextLabel.setText(_translate("MainWindow", "Введите текст:"))
        self.AuthorLabel.setText(_translate("MainWindow", "Введите имя автора:"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить заметку"))

    def save_note(self):
        with open(f"{datetime.datetime.now()}.txt", "w") as f:
            f.write(f"{datetime.datetime.now()}\n{self.TitleLine.text()}\n{self.textEdit.toPlainText()}\n{self.AuthorLine.text()}")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
